services:
  app:
    build: .
    container_name: gin_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env.development
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8081:8080"
    restart: always

volumes:
  postgres_data: